plantgroup1987/MyPetLink

- templates/home.html
- templates/profile.html
Updated cities and states in Profile page
> Updated profile location data

- templates/base.html
- templates/home.html
- Added GA tracking code to base.html
- Updated Title shown in browser 
- Added favicon
> updated google tag

- app.py
- static/js/pet_app.js
- templates/home.html
> pet finder api integration

- app.py
- static/js/pet_app.js
- templates/base.html
- templates/home.html
> Added PetFinder API integration 

- templates/home.html
mobile optimization for adopt a pet button
> mobile optimized buttons

- app.py
- templates/home.html
- templates/profile.html
- Fixed button sizing for rescue tickets
- Added American Bully and Mixed Breed to breeds 
- Added Puerto Rico and its cities to Profile location
> updated breeds

- gpt_agent.py
- static/js/pet_app.js
> Poop analysis bug fixed 

- app.py
- templates/base.html
- templates/data_use.html
- templates/privacy.html
added privacy policy and data use agreement
> added privacy policy and data use agreement

- app.py
- models.py
- templates/base.html
- templates/home.html
- templates/profile.html
> vaccination reminder added

- templates/home.html
updated vaccine reminder to annual
> updated reminder to annual

- templates/base.html
> added Google AdSense

- templates/profile.html
remove state and city from location
> profile updated

- templates/base.html
- templates/profile.html
remvoed state and city from profile location
> updated profile location

- app.py
- database.py
- models.py
- templates/profile.html
> Vet info added to profile

- app.py
- templates/base.html
- templates/home.html
- templates/matches.html
- templates/messages.html
- Add matching algorithm with location and preferences
- Create matches.html for matching UI
- Create messages.html for chat interface
- Update base.html and home.html with navigation
- Add API endpoints for matches and messages
> feat: implement matching and chat system

- templates/data_use.html
- templates/home.html
- templates/privacy.html
- templates/profile.html
> fixed double nav on mobile

- app.py
- templates/base.html
> fixed mobile nav issues

- app.py
- templates/base.html
> fixed mobile nav

- templates/profile.html
> fixed pet profiles

- app.py
- templates/matches.html
> fixed match bug

- app.py
- templates/matches.html
- templates/profile.html
> matching algo bug fixed

- app.py
- templates/base.html
- templates/dashboard.html
> added Dashboard page
